FROM registry.dev.zextras.com/dev/carbonio-sidecar:latest

# Service registration
COPY proxy/carbonio-proxy.hcl /consul/config/

# Setup script
COPY proxy/carbonio-proxy.sh /usr/local/bin/carbonio-proxy
RUN chmod +x /usr/local/bin/carbonio-proxy

ENV SERVICE_NAME=carbonio-proxy
ENV SETUP_SCRIPT="carbonio-proxy setup"
ENV ENVOY_EXTRA_ARGS="-grpc-addr=localhost:8502"