# syntax=docker/dockerfile:1.4
FROM registry.dev.zextras.com/dev/carbonio-sidecar:devel

# Service registration
COPY proxy/carbonio-proxy.hcl /consul/config/

# Setup files
COPY proxy/service-protocol-proxy.json /etc/carbonio/proxy/service-discover/service-protocol.json
COPY proxy/policies-proxy.json /etc/carbonio/proxy/service-discover/policies.json

# Setup script
COPY --chmod=755 proxy/carbonio-proxy.sh /usr/local/bin/carbonio-proxy

ENV SERVICE_NAME=carbonio-proxy
ENV SETUP_SCRIPT="carbonio-proxy setup"
ENV TOKEN_FILE=/etc/carbonio/proxy/service-discover/token