#!/bin/bash

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ "$1" != "setup" ]]; then
  echo "Syntax: carbonio-proxy <setup> to automatically setup the service"
  exit 1;
fi

# decrypt the bootstrap token, asking the password to the sys admin
# --setup check for SETUP_CONSUL_TOKEN env. variable and uses it
# to avoid re-asking for the password multiple times
echo -n "insert the cluster credential password: "
export CONSUL_HTTP_TOKEN=$(service-discover bootstrap-token --setup)
EXIT_CODE="$?"
echo ""
if [[ "${EXIT_CODE}" != "0" ]]; then
  echo "cannot access to bootstrap token"
  exit 1;
fi
# limit secret visibility as much as possible
export -n SETUP_CONSUL_TOKEN

POLICY_NAME='carbonio-proxy-policy'
POLICY_DESCRIPTION='Carbonio Proxy service policy for config generation and for sidecar proxy'
POLICY_RULES="$(cat <<EOF
"key_prefix" = {
  "carbonio-proxy/" = {
    "policy" = "read"
  }
}
"node_prefix" = {
  "" = {
    "policy" = "read"
  }
}
"service" = {
  "carbonio-proxy" = {
    "policy" = "write"
  }
  "carbonio-proxy-sidecar-proxy" = {
    "policy" = "write"
  }
}
EOF
)"

# create or update policy for the specific service (this will be shared across cluster)
consul acl policy create -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules "${POLICY_RULES}" >/dev/null 2>&1
if [[ "$?" != "0" ]]; then
    consul acl policy update -no-merge -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules "${POLICY_RULES}"
    if [[ "$?" != "0" ]]; then
      echo "Setup failed: Cannot update policy for ${POLICY_NAME}"
      exit 1
    fi
fi

# declare the service as http
cat <<EOF | consul config write -
{
  "kind": "service-defaults",
  "name": "carbonio-proxy",
  "protocol": "http"
}
EOF

# Allow other services to contact this service
consul config write "/etc/carbonio/proxy/service-discover/intentions.json"

if [[ ! -f "/etc/zextras/carbonio-proxy/token" ]]; then
    # create the token
    consul acl token create -format json -policy-name "${POLICY_NAME}" -description "Token for carbonio-proxy/$(hostname -A)" |
      jq -r '.SecretID' > /etc/zextras/carbonio-proxy/token;
    chown carbonio-proxy:carbonio-proxy /etc/zextras/carbonio-proxy/token
    chmod 0600 /etc/zextras/carbonio-proxy/token
fi

consul reload

# limit token visibility as much as possible
export -n CONSUL_HTTP_TOKEN

systemctl restart carbonio-proxy-sidecar.service
